export const projects = [
  {
    num: '01',
    category: 'Mobile App Project',
    title: 'LanderUp - P2P Lending App',
    description: 'A peer-to-peer (P2P) lending mobile application that connects borrowers and lenders to conduct transactions. This application focuses on funding MSMEs to advance the middle to lower economy.',
    stack: ['Flutter', 'FastAPI', 'Figma'],
    role: ['UI/UX Researcher', 'Mobile Developer', 'Backend Developer'],
    image: '/assets/work/landerup.png',
    live: '#',
    github: 'https://github.com/MuhammadRizki8/LenderUp',
  },
  {
    num: '02',
    category: 'Mobile App Project',
    title: 'Minatku',
    description: 'MinatKu is a career and college-prep application created to fulfill the capstone project in the Bangkit programme. The application can provide suitable career path suggestions for users using AI.',
    stack: ['Android', 'Tensorflow', 'Flask', 'Google Cloud Platform'],
    role: ['Backend Developer', 'Cloud Engineer'],
    image: '/assets/work/minatku.png',
    live: '#',
    github: 'https://github.com/minatku',
  },
  {
    num: '03',
    category: 'Web App Project',
    title: 'Profile SMA 13 Bandung',
    description: 'A school profile website for SMA 13 Bandung that displays information about school programs, achievements, and activities. Built using Laravel with an admin panel to manage content dynamically.',
    stack: ['Laravel'],
    role: ['Web Developer'],
    image: '/assets/work/school.png',
    live: '#',
    github: 'https://github.com/MuhammadRizki8/laravel-school-profile',
  },
  {
    num: '04',
    category: 'Web App Project',
    title: 'Donasi Mahasiswa UPI',
    description: '"Peduli Mahasiswa" is a student donation website application that facilitates online donations. Built using WordPress, integrated with the TriPay payment gateway to manage secure transactions.',
    stack: ['WordPress', 'TriPay'],
    role: ['Web Developer'],
    image: '/assets/work/donasi.png',
    live: '#',
    github: 'https://github.com/MuhammadRizki8/Website-Donasi-Peduli-Mahasiswa',
  },
  {
    num: '05',
    category: 'Web Design Project',
    title: 'Malala',
    description: 'Malala is a Minangkabau cultural tourism promotion website. It showcases the rich heritage and attractions of the Minangkabau culture to attract both local and international tourists.',
    stack: ['Figma', 'React', 'TailwindCSS'],
    role: ['UI/UX Designer', 'Frontend Developer'],
    image: '/assets/work/malala.png',
    live: 'http://malala.vercel.app/',
    github: 'https://github.com/MuhammadRizki8/malala',
  },
  {
    num: '06',
    category: 'UI/UX Project',
    title: 'PeerPocket',
    description: 'A financial management app that integrates with multiple sources whether bank, ewallet, cash, etc. The app helps users to track and manage their finances from multiple sources in a seamless and efficient manner.',
    stack: ['Figma'],
    role: ['UX Researcher'],
    image: '/assets/work/peerpocket.png',
    live: 'https://www.canva.com/design/DAGH1NHwkDs/7GWRoPx29GMtMtQeTInFpA/view?utm_content=DAGH1NHwkDs&utm_campaign=designshare&utm_medium=link&utm_source=editor',
    github: 'https://www.canva.com/design/DAGH1NHwkDs/7GWRoPx29GMtMtQeTInFpA/view?utm_content=DAGH1NHwkDs&utm_campaign=designshare&utm_medium=link&utm_source=editor',
  },
];
