import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import StairTransition from '@/components/StairTransition';

// Mengimpor font JetBrains Mono
const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'], // Anda bisa menyesuaikan subset-nya sesuai kebutuhan
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'], // Pilih berat font yang ingin digunakan
  variable: '--font-jetbrains-mono', // Variabel CSS untuk digunakan dalam aplikasi
});

export const metadata = {
  title: 'Rizki',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} antialiased`}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
